### PR TITLE
fix centring on macOS

### LINKED ISSUE #3: splash screen not aligned vertically
it appears somewhere in the first third of the screen for me

### PR DESCRIPTION
**Pull request by tzapu**
fixes https://github.com/wojtkowiak/meteor-desktop-splash-screen/issues/3

### CODE REVIEW

**Comment by wojtkowiak** [comment]
On what OSX version you are experiencing this problem?
This seems weir because `center` is true by default unless you pass x or y coordinates. So in theory this should change nothing.
Seems like an issue with Electron.
Did you test this change on Window and Linux?

**Comment by wojtkowiak** [comment]
Please rebase this into one commit.

**Comment by tzapu** [comment]
hi, tested on windows 10, all ok (the problem didn't appear on win 10 anyway), no chance to test it on linux though.
macOS Sierra 10.12.2 (16C67)
will close this pull request and make another with just one change as i did it in the github web interface and i don t know how to rebase without checking it out locally

**Comment by tzapu** [comment]
added https://github.com/wojtkowiak/meteor-desktop-splash-screen/pull/6

**Pull request closed without merging**
